name: feature request
description: something new
body:
  - type: textarea
    id: freeform
    attributes:
      label: describe your actual problem
      placeholder: 'I want to do ... I tried ... It does not work because ...'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: pre-commit --version
      placeholder: pre-commit x.x.x
    validations:
      required: false
